from pathlib import Path
import json
p=Path('outputs/honglou-garden-image-v1');old=Path('outputs/honglou-garden-detail-v1')
data=json.loads((old/'garden-data.json').read_text());coords={
'xiaoxiang':([.112,.255],[.105,.21,.20,.14]),'yihong':([.092,.51],[.105,.40,.21,.19]),'hengwu':([.505,.174],[.42,.13,.145,.145]),'qiushuang':([.815,.235],[.68,.15,.21,.205]),'daoxiang':([.675,.673],[.60,.61,.23,.17]),'ouxiang':([.84,.535],[.745,.43,.165,.15])}
for n in data['nodes']:
 n['anchor'],n['region']=coords[n['id']];n['crop']=[max(0,n['region'][0]-.055),max(0,n['region'][1]-.055),min(.99,n['region'][2]+.11),min(.99,n['region'][3]+.11)]
 n['basis']=n['basis'].replace('艺术化白模','艺术化插画').replace('尺度为艺术化简化','画面尺度为艺术化安排')
 if n['id']=='qiushuang':n['summary']='探春居所，与晓翠堂的食事线索相连；画面外形为艺术化设计。'
(p/'garden-data.json').write_text(json.dumps({'version':'garden-image-v1','nodes':data['nodes']},ensure_ascii=False,indent=2))
html=(old/'index.html').read_text();start=html.index('<section id="map"');end=html.index('<details id="places"')
html=html[:start]+'''<section id="map" tabindex="0" aria-label="二维插画地图。方向键平移，正负号缩放，Home恢复总览"><div id="loading" role="status">正在展开大观园画卷…</div><div id="picture"><img id="garden-image" src="/assets/garden-clean.png" alt="大观园六景插画，竹院、蕉窗、山石、田舍与水榭" draggable="false"><svg id="hotspots" viewBox="0 0 1000 1000" preserveAspectRatio="none" aria-hidden="true"></svg></div><div id="labels"></div><div id="load-error" hidden role="alert">园林图片未能加载。<button id="retry">重新加载</button><p>仍可通过居所一览查看六景资料。</p></div></section>'''+html[end:]
html=html.replace('<button id="mode" aria-pressed="false">旋转看园</button><span class="control-divider"></span>','').replace('三维场景实景','地图局部').replace('<img id="detail-image" alt="">','<div id="detail-image" role="img"></div>')
html=html.replace('<span aria-hidden="true">▤</span>','<span aria-hidden="true">📖</span>').replace('<span class="book-icon" aria-hidden="true">匣</span>','<span class="book-icon" aria-hidden="true">匣</span>')
(p/'index.html').write_text(html);(p/'garden/index.html').write_text(html)
(p/'styles.css').write_text((old/'styles.css').read_text()+'''
/* 图片版沿用参考图控件，213px阅读栏。 */
main{min-height:0}#map{inset:96px 18px 110px;overflow:hidden;cursor:grab}body.panel-open #map{right:251px}#map:active{cursor:grabbing}#picture{position:absolute;left:0;top:0;transform-origin:0 0;pointer-events:none}#garden-image{display:block;width:100%;height:100%;user-select:none;-webkit-user-drag:none}#hotspots{position:absolute;inset:0;width:100%;height:100%;pointer-events:none}#hotspots rect{fill:transparent;pointer-events:auto;cursor:pointer}#labels{inset:0;z-index:2}.label{transform:translate(-50%,-50%);font-size:17px;padding:9px 6px;letter-spacing:3px;background:#fff8e8f7}.label.selected{border-color:#963b4c;background:#fff0e0}.reading-pane{width:213px;right:18px;top:98px;bottom:112px;padding:32px 15px 18px}.reading-pane h1{font-size:30px;letter-spacing:3px;line-height:1.4;margin:12px 0 5px}.reading-pane p{font-size:15px;line-height:1.8}#resident{font-size:17px;letter-spacing:1px;margin:7px 0 18px}#summary{font-size:16px;text-align:left;margin:16px 0}.basis summary{font-size:13px;line-height:1.5}.basis p{font-size:14px!important}#detail-image{width:100%;aspect-ratio:1.15;background-image:url('/assets/garden-clean.png');background-repeat:no-repeat}figure{margin:0 0 14px}#food,#panel-back{font-size:18px;letter-spacing:2px;min-height:48px}#close{right:5px;top:4px}footer{left:245px;right:310px;bottom:25px}.controls{right:18px;bottom:31px}#places{bottom:31px}.controls button{font-size:25px}.controls #reset{font-size:17px;padding:9px 16px}.controls output{font-size:18px;min-width:59px}.help{font-size:13px}.caption{font-size:13px}.brand{font-size:38px}header{padding:20px 29px 0}nav button{font-size:20px}#loading,#load-error{position:absolute;inset:42% 0 auto;text-align:center;z-index:4}#load-error{background:#fff9edee;padding:25px}dialog{font-size:16px}#dialog-close{position:absolute}.label[hidden]{display:none}
@media(max-width:1100px) and (min-width:701px){#map{right:18px}body.panel-open #map{right:251px}.reading-pane{width:213px;right:18px}footer{left:220px;right:295px}.help{font-size:11px}.brand{font-size:30px}nav button{font-size:16px}}
@media(max-width:700px){header{padding:18px 14px 0}.brand{font-size:23px;letter-spacing:2px}.seal{width:26px;height:45px}nav{gap:2px}nav button{font-size:12px;gap:3px;padding:8px 3px}.brand small{font-size:12px}main{min-height:0}#map,body.panel-open #map{inset:83px 0 178px}.label{font-size:13px;padding:6px 4px;letter-spacing:2px}#places{left:14px;bottom:113px}.controls{left:14px;right:14px;bottom:56px}.controls #reset{font-size:14px}.controls output{font-size:16px}.controls button{font-size:22px}footer{left:5px;right:5px;bottom:13px}.help{font-size:10px}.caption{font-size:11px}#panel{top:auto;bottom:166px;left:14px;right:14px;width:auto;max-height:52dvh;padding:27px 20px 18px}#panel h1{font-size:29px}#panel figure{width:100%;max-width:240px;margin:12px auto}#detail-image{aspect-ratio:1.5}#summary{font-size:16px}.reading-pane p{font-size:15px}#panel #food,#panel-back{font-size:17px}#list button{min-height:44px}}
''')
(p/'docs/design/implementation-plan.md').write_text('''# 二维插画地图实施计划\n\n目标：将用户确认的参考图转为本地图片交互地图，保留参考控件，右栏213px。\n实现：底图、归一化节点配置、view.js视图数学、map.js手势、app.js面板分离。原文件只读。\n\n- [x] imagegen局部清理底图，保留原图对照。\n- [ ] 测试指针锚点、缩放范围、边界、resize与复位；实现视图和手势。\n- [ ] 沿用HTML控件与六景资料，窄栏、局部图、移动底部阅读面板。\n- [ ] 浏览器检查鼠标/触屏/键盘/面板状态、截图与交付。\n\n配色：绢白#f5eddf、纸白#fff9ed、胭脂#7c303e、旧金#b29058、木棕#63472c。字体宋体，标题38px，说明正文16px。园林疏密与池形沿用参考，网页仅补充必要可读标签；无新增工具栏。用户本轮详细要求已作为确认设计，直接实施。\n''')
