-- Public, read-only catalogue tables. Apply in Supabase SQL Editor before import.

create table if not exists public.source_book (
  id text primary key,
  short_name text not null unique,
  title text not null,
  author text not null
);

create table if not exists public.catalog_entity (
  id text primary key,
  name text not null,
  categories jsonb not null default '[]'::jsonb,
  decisions jsonb not null default '[]'::jsonb,
  novel_candidate boolean not null default false
);

create table if not exists public.entity_alias (
  entity_id text not null references public.catalog_entity(id) on delete cascade,
  alias text not null,
  kind text not null,
  primary key (entity_id, alias)
);

create table if not exists public.source_occurrence (
  id text primary key,
  entity_id text not null references public.catalog_entity(id) on delete restrict,
  source_book_id text not null references public.source_book(id) on delete restrict,
  name text not null,
  category text,
  decision text,
  pdf_page integer,
  printed_page integer,
  source_page_id text,
  source_locator text not null,
  notes text not null default '',
  source_transcription text not null default '',
  verification_status text not null default '',
  semantic_verification text not null default '',
  organization_status text not null default '',
  chapter_hints jsonb not null default '[]'::jsonb,
  assertion_boundary text not null default '来源作者说法'
);

create table if not exists public.entity_relation (
  id bigint generated by default as identity primary key,
  from_entity_id text not null references public.catalog_entity(id) on delete cascade,
  to_entity_id text not null references public.catalog_entity(id) on delete cascade,
  relation_type text not null,
  note text not null default '',
  unique (from_entity_id, to_entity_id, relation_type)
);

create index if not exists catalog_entity_name_idx on public.catalog_entity(name);
create index if not exists catalog_entity_categories_gin_idx on public.catalog_entity using gin(categories);
create index if not exists entity_alias_alias_idx on public.entity_alias(alias);
create index if not exists source_occurrence_entity_idx on public.source_occurrence(entity_id);
create index if not exists source_occurrence_book_page_idx on public.source_occurrence(source_book_id, pdf_page);
create index if not exists source_occurrence_search_idx on public.source_occurrence using gin (
  to_tsvector('simple', coalesce(name, '') || ' ' || coalesce(notes, '') || ' ' || coalesce(category, ''))
);

alter table public.source_book enable row level security;
alter table public.catalog_entity enable row level security;
alter table public.entity_alias enable row level security;
alter table public.source_occurrence enable row level security;
alter table public.entity_relation enable row level security;

revoke all on table public.source_book, public.catalog_entity, public.entity_alias, public.source_occurrence, public.entity_relation from anon, authenticated;
grant usage on schema public to anon;
grant select on table public.source_book, public.catalog_entity, public.entity_alias, public.source_occurrence, public.entity_relation to anon;

drop policy if exists "public catalogue read" on public.source_book;
create policy "public catalogue read" on public.source_book for select to anon using (true);
drop policy if exists "public catalogue read" on public.catalog_entity;
create policy "public catalogue read" on public.catalog_entity for select to anon using (true);
drop policy if exists "public catalogue read" on public.entity_alias;
create policy "public catalogue read" on public.entity_alias for select to anon using (true);
drop policy if exists "public catalogue read" on public.source_occurrence;
create policy "public catalogue read" on public.source_occurrence for select to anon using (true);
drop policy if exists "public catalogue read" on public.entity_relation;
create policy "public catalogue read" on public.entity_relation for select to anon using (true);
